# Generated by Django 4.2.8 on 2025-09-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawIngest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('endpoint', models.CharField(max_length=64)),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('payload', models.JSONField()),
                ('ts_event', models.DateTimeField(blank=True, null=True)),
                ('ts_ingested', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpotSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('quote_ccy', models.CharField(default='KRW', max_length=8)),
                ('source', models.CharField(default='upbit', max_length=32)),
                ('ts_event', models.DateTimeField(db_index=True)),
                ('ts_ingested', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('interval', models.CharField(max_length=8)),
                ('open', models.DecimalField(decimal_places=8, max_digits=20)),
                ('high', models.DecimalField(decimal_places=8, max_digits=20)),
                ('low', models.DecimalField(decimal_places=8, max_digits=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=24, null=True)),
                ('ts_open', models.DateTimeField(db_index=True)),
                ('source', models.CharField(default='coinpaprika', max_length=32)),
                ('ts_ingested', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('symbol', 'interval', 'ts_open', 'source')},
            },
        ),
    ]
