# Generated by Django 4.2.8 on 2025-09-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market24hStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('acc_trade_price_24h', models.DecimalField(decimal_places=8, max_digits=30)),
                ('acc_trade_volume_24h', models.DecimalField(decimal_places=8, max_digits=30, null=True)),
                ('source', models.CharField(default='upbit', max_length=32)),
                ('ts_event', models.DateTimeField(db_index=True)),
                ('ts_ingested', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'index_together': {('symbol', 'ts_event')},
            },
        ),
    ]
