# Generated by Django 4.2.8 on 2025-09-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0002_market24hstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto24hRawIngest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('endpoint', models.CharField(max_length=64)),
                ('symbol', models.CharField(db_index=True, max_length=128)),
                ('payload', models.JSONField()),
                ('ts_event', models.DateTimeField(blank=True, null=True)),
                ('ts_ingested', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'crypto_24hr_rawingest',
                'indexes': [models.Index(fields=['symbol', 'ts_event'], name='crypto_24hr_symbol_c9e892_idx')],
            },
        ),
    ]
