# Generated by Django 4.2.8 on 2025-09-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0003_crypto24hrawingest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto24hRawIngestLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('endpoint', models.CharField(max_length=64)),
                ('request_params', models.JSONField(blank=True, null=True)),
                ('http_status', models.IntegerField()),
                ('headers', models.JSONField()),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(db_index=True)),
                ('duration_ms', models.IntegerField()),
            ],
            options={
                'db_table': 'crypto_24hr_rawingest_landing',
            },
        ),
        migrations.DeleteModel(
            name='Crypto24hRawIngest',
        ),
    ]
