# Generated by Django 4.2.8 on 2025-09-30 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bitcoin', '0004_crypto24hrawingestlanding_delete_crypto24hrawingest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto24hRawIngestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('symbol', models.CharField(max_length=128)),
                ('ts_event', models.DateTimeField(db_index=True)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(db_column='call_id', on_delete=django.db.models.deletion.CASCADE, to='bitcoin.crypto24hrawingestlanding')),
            ],
            options={
                'db_table': 'crypto_24hr_rawingest_events',
            },
        ),
    ]
